version: 2.0

jobs:
  unit-tests:
    docker:
      - image: circleci/openjdk:stretch
    resource_class: medium
    working_directory: ~/inquiry-data-pipeline
    steps:
      - checkout
      - restore_cache:
          keys:
            - inquiry-data-pipeline-cache-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml fi
      - run: 
          name: Installation of imagemagick
          command: |
            sudo sed -i -e 's/deb.debian.org/archive.debian.org/g' -e 's|security.debian.org|archive.debian.org/|g' -e '/stretch-updates/d' /etc/apt/sources.list
            sudo rm /etc/apt/sources.list.d/stretch-backports.list
            sudo apt-get update || sudo apt-get update
            sudo apt-get install -y imagemagick
      - run:
          name: Execute coverage report
          command: |
            mvn clean scoverage:report -DCLOUD_STORE_GROUP_ID=$CLOUD_STORE_GROUP_ID -DCLOUD_STORE_ARTIFACT_ID=$CLOUD_STORE_ARTIFACT_ID -DCLOUD_STORE_VERSION=$CLOUD_STORE_VERSION
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - save_cache:
            paths:
              - ~/.m2
            key: inquiry-data-pipeline-cache-{{ checksum "pom.xml" }}
      - store_test_results:
          path: ~/test-results
      - run:
           name: sonar
           command: |
             mvn -X sonar:sonar -Dlog4j.configuration=./logs sonar:sonar -Dsonar.projectKey=Sunbird-inQuiry_data-pipeline -Dsonar.organization=sunbird-inquiry -Dsonar.host.url=https://sonarcloud.io -Dsonar.scala.coverage.reportPaths=/home/circleci/inquiry-data-pipeline/target/scoverage.xml

workflows:
  version: 2
  build-and-test:
    jobs:
      - unit-tests